name    'razorsedge-cloudera'
version '0.0.1'
author 'razorsedge'
license 'Apache License, Version 2.0'
project_page 'https://github.com/razorsedge/puppet-cloudera'
source 'git://github.com/razorsedge/puppet-cloudera.git'
summary 'UNKNOWN'
description 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>=2.3.0'
dependency 'puppetlabs/mysql', '>=0.6.0'
dependency 'puppetlabs/postgresql', '>=2.0.0'
#dependency 'puppetlabs/java', '>=0.2.0'
dependency 'maestrodev/wget', '>=1.0.0'
